[versioning]
strategy = "pep440"  # valid values: 440, semver, commitizen, date, gitcount

[release]
custom_author = "devalltect00"
include_date = true

# ----------------------------------------------#
# source: https://github.com/devalltect00/Custy #
# ----------------------------------------------#