[project]
name = "git_reflow"

[docker]
provider = "both" # github | gitlab | both

[github]
image = "ghcr.io/devalltect00/git_reflow"

[gitlab]
image = "registry.gitlab.com/devalltect00/git_reflow"

# -----------------------------------------------------------------------------#
# source: https://github.com/devalltect00/git_reflow/pkgs/container/git_reflow #
# -----------------------------------------------------------------------------#