flowchart TD

A[Install Reflow]
B[reflow init]
C[Edit config.toml]

D[reflow tags convert local or remote]
E[reflow releases recover]
F[reflow dockerize]

G[Git Tags]
H[GitHub Releases]
I[Container Registry]

A --> B
B --> C

C --> D
C --> E
C --> F

D --> G
E --> H
F --> I
